# Generated by Django 2.2.4 on 2019-11-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companiess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('img', models.ImageField(upload_to='pics')),
                ('website', models.CharField(max_length=100)),
            ],
        ),
    ]
